parameters:
    ###> DEFAULT ###
    gs_service.locale:                      'en_US'
    gs_service.timezone:                    '+0000'
    gs_service.app_env:                     '%env(APP_ENV)%'
    gs_service.local_drive_for_test:        ''
    gs_service.year_regex:                  '(?:\b[0-9]{4}\b|\b[0-9]{2}\b)'
    gs_service.year_regex_full:             '[0-9]{4}'
    gs_service.ip_v4_regex:                 '(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)'
    gs_service.slash_of_ip_regex:           '[/\\]{1,2}'
    gs_service.start_of_win_sys_file_regex: '\~[$]'
    gs_service.load_packs_configs:          []
    ###< DEFAULT ###

services:
    _defaults:
        public:             false
        autowire:           false
        autoconfigure:      false
        
        bind:
            ###> VALUES ###
            #$gsServiceAppEnv:             '%gs_service.app_env%'
            #$gsServiceProjectDir:         '%kernel.project_dir%'
            #$gsServicePackageFilenames:   '%gs_service.load_packs_configs%'
            #$gsServiceLocalDriveForTest:  '%gs_service.local_drive_for_test%'
            #$gsServiceYearRegex:          '%gs_service.year_regex%'
            #$gsServiceYearRegexFull:      '%gs_service.year_regex_full%'
            #$gsServiceIpV4Regex:          '%gs_service.ip_v4_regex%'
            #$gsServiceSlashOfIpRegex:     '%gs_service.slash_of_ip_regex%'
            ###< VALUES ###
            
            ###> SERVICES ###
            
            ###> BUNDLE SERVICES (You can use them by @<name> in your services.yaml) ###
            #$gsServiceFaker: '@gs_service.faker'
            $gsServiceCarbonFactoryImmutable:    '@gs_service.carbon_factory_immutable'
            ###< BUNDLE SERVICES (You can use them by @<name> in your services.yaml) ###
            
            ###> LIB SERVICES ###
            # TODO: 0 replace t to this in this project
            #$gsServiceT: '@Symfony\Contracts\Translation\TranslatorInterface'
            ###< LIB SERVICES ###
            
            ###< SERVICES ###